PROMPT_SCHEMA_VERSION = 'v1'

MAX_SESSION_SUMMARY_MESSAGES = 6
MAX_SESSION_SUMMARY_CHARS = 240
MAX_TIMELINE_LINE_CHARS = 160
MAX_REASON_CHARS = 90
MAX_PARAMETER_CHARS = 72
MAX_RECENT_DETAIL_COUNT = 3
MAX_INSTALLED_APPS = 12
